"""
seed_db.py  –  Bootstrap the database with the minimum required data.

Only creates the admin user if it doesn't already exist.
All real data (hospitals, doctors, nurses, patients) must be entered
through the application UI by the admin.

Fake vitals are generated automatically by the scheduler
whenever a real patient exists in the system.

Run:  python seed_db.py
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from database import SessionLocal, engine, Base
from models import User
from auth import hash_password

ADMIN_USERNAME = os.getenv("ADMIN_USERNAME", "admin")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD")

# Ensure all tables exist
Base.metadata.create_all(bind=engine)

db = SessionLocal()

try:
    # ── Check if admin already exists ────────────────────────────────────────
    existing_admin = db.query(User).filter(User.role == "ADMIN").first()
    if existing_admin:
        print("⚠️  Admin user already exists. Skipping seed.")
        print(f"   Admin username: {existing_admin.username}")
        sys.exit(0)

    # ── Create admin user only ────────────────────────────────────────────────
    if not ADMIN_PASSWORD:
        raise RuntimeError("ADMIN_PASSWORD must be set to create the initial admin user.")
    weak_passwords = {"admin123", "password", "change-me", "changeme", "admin"}
    if ADMIN_PASSWORD.lower() in weak_passwords or len(ADMIN_PASSWORD) < 12:
        raise RuntimeError("ADMIN_PASSWORD is too weak. Use at least 12 characters and avoid default values.")

    admin = User(
        username=ADMIN_USERNAME,
        password_hash=hash_password(ADMIN_PASSWORD),
        role="ADMIN",
    )
    db.add(admin)
    db.commit()

    print("=" * 50)
    print("✅ Admin user created successfully!")
    print("=" * 50)
    print("\n📋 Login credentials:")
    print(f"   Username: {ADMIN_USERNAME}")
    print("   Password: [hidden]")
    print("\nℹ️  Add hospitals, doctors, nurses and patients")
    print("   through the application after logging in.")
    print("\nℹ️  Fake vitals are auto-generated by the")
    print("   scheduler for every patient in the system.")
    print()

except Exception as e:
    db.rollback()
    print(f"❌ Seed failed: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)
finally:
    db.close()
