"""
seed_db.py  –  Bootstrap the database with the minimum required data.

Only creates the admin user if it doesn't already exist.
All real data (hospitals, doctors, nurses, patients) must be entered
through the application UI by the admin.

Fake vitals are generated automatically by the scheduler
whenever a real patient exists in the system.

Run:  python seed_db.py
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

from database import SessionLocal, engine, Base
from models import User
from auth import hash_password
from sqlalchemy import text

ADMIN_USERNAME = os.getenv("ADMIN_USERNAME", "admin")
ADMIN_PASSWORD = os.getenv("ADMIN_PASSWORD")

# ── Auto-apply critical schema updates (for Render bypass) ───────────────
print("Applying critical schema updates...")
with SessionLocal() as mig_db:
    try:
        if engine.name == "postgresql":
            mig_db.execute(text("ALTER TABLE audit_logs ADD COLUMN IF NOT EXISTS details VARCHAR(1000);"))
            mig_db.execute(text("ALTER TABLE alert_escalations ALTER COLUMN escalated_to_doctor DROP NOT NULL;"))
            
            # Relax Vitals constraints
            mig_db.execute(text("ALTER TABLE vitals DROP CONSTRAINT IF EXISTS ck_vitals_heart_rate_range;"))
            mig_db.execute(text("ALTER TABLE vitals ADD CONSTRAINT ck_vitals_heart_rate_range CHECK (heart_rate BETWEEN 0 AND 300);"))
            
            mig_db.execute(text("ALTER TABLE vitals DROP CONSTRAINT IF EXISTS ck_vitals_spo2_range;"))
            mig_db.execute(text("ALTER TABLE vitals ADD CONSTRAINT ck_vitals_spo2_range CHECK (spo2 BETWEEN 0 AND 100);"))
            
            mig_db.execute(text("ALTER TABLE vitals DROP CONSTRAINT IF EXISTS ck_vitals_temperature_range;"))
            mig_db.execute(text("ALTER TABLE vitals ADD CONSTRAINT ck_vitals_temperature_range CHECK (temperature BETWEEN 50 AND 150);"))
            
            mig_db.commit()
            print("Schema updates verified.")
    except Exception as e:
        mig_db.rollback()
        print(f"Migration note (safe to ignore if applied): {e}")

# Ensure all tables exist
Base.metadata.create_all(bind=engine)

db = SessionLocal()

try:
    # ── Check if admin already exists ────────────────────────────────────────
    existing_admin = db.query(User).filter(User.role == "ADMIN").first()
    if existing_admin:
        print("⚠️  Admin user already exists. Skipping seed.")
        print(f"   Admin username: {existing_admin.username}")
        sys.exit(0)

    # ── Create admin user only ────────────────────────────────────────────────
    if not ADMIN_PASSWORD:
        raise RuntimeError("ADMIN_PASSWORD must be set to create the initial admin user.")
    
    if len(ADMIN_PASSWORD) < 8:
        raise RuntimeError("ADMIN_PASSWORD is too weak. Use at least 8 characters.")

    weak_passwords = {"password", "admin123", "changeme", "admin"}
    if ADMIN_PASSWORD.lower() in weak_passwords:
        print("⚠️  WARNING: Using a very common ADMIN_PASSWORD. Highly recommended to change this in production.")

    admin = User(
        username=ADMIN_USERNAME,
        password_hash=hash_password(ADMIN_PASSWORD),
        role="ADMIN",
    )
    db.add(admin)
    db.commit()

    print("=" * 50)
    print("✅ Admin user created successfully!")
    print("=" * 50)
    print("\n📋 Login credentials:")
    print(f"   Username: {ADMIN_USERNAME}")
    print("   Password: [hidden]")
    print("\nℹ️  Add hospitals, doctors, nurses and patients")
    print("   through the application after logging in.")
    print("\nℹ️  Fake vitals are auto-generated by the")
    print("   scheduler for every patient in the system.")
    print()

except Exception as e:
    db.rollback()
    print(f"❌ Seed failed: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)
finally:
    db.close()
